let data = {
    "High Deck": "The cards that compose the High Deck aren't considered to be one suit, although they are often denoted with a crown icon to mark their importance. Rather, each card is an important power in its own right. If one of these cards comes out in a casting and seems to contradict the prediction of an earlier card, the Vistani always assume that this card takes precedence.",
    "Swords Suit": "The Swords suit symbolizes aggression and violence. It is the suit of warriors, be they paladins, soldiers, mercenaries, or gladiators. It also symbolizes the power of governments and leaders, whether noble or corrupt.",
    "Stars Suit": "The Stars suit symbolizes the desire for personal power and control over things beyond the ken of mortals. It is the suit of arcane mages, sages, and intellectuals. It also represents the triumph of magic, science, and reason over religion, mysticism, and superstition.",
    "Coins Suit": "The Coins suit symbolizes avarice and the desire for personal and material gain. It is also symbolic of gluttony, lust, and obsession. On the side of good, this suit can suggest the accumulation of wealth for the benefit of a charity or a just cause. On the side of evil, it embodies the worst aspects of greed. It speaks to the power of gold, and how that power can build or destroy nations.",
    "Glyphs Suit": "The Glyphs suit symbolizes faith, spirituality, and inner strength. It is the suit of priests and those who devote themselves to the service of a deity, a higher power, or a heightened philosophy. On the side of good, it represents willpower and dedication. On the side of evil, the suit signifies weakness of character, self-doubt, and betrayal of one's ideals or beliefs. It symbolizes health and healing, as well as illness and disease.",
    "cards": {
        "High Deck - Artifact": "Represents the importance of some physical object that must be obtained, protected, or destroyed at all costs",
        "High Deck - Beast": "Represents great rage or passion -- something bestial or malevolent hiding in plain sight or lurking just below the surface",
        "High Deck - Broken One": "Represents defeat, failure, and despair -- the loss of something or someone important, without which one feels incomplete",
        "High Deck - Darklord": "Represents a single, powerful individual of an evil nature, one whose goals have enormous and far-reaching consequences",
        "High Deck - Donjon": "Represents isolation and imprisonment -- being so conservative in thinking as to be a prisoner of one's own beliefs",
        "High Deck - Ghost": "Represents the looming past -- the return of an old enemy or the discovery of a secret buried long ago",
        "High Deck - Executioner": "Represents the imminent death of one rightly or wrongly convicted of a crime -- false accusations and unjust prosecution",
        "High Deck - Horseman": "Represents death -- disaster in the form of the loss of wealth or property, a horrible defeat, or the end of a bloodline",
        "High Deck - Innocent": "Represents a being of great importance whose life is in danger (who might be helpless or simply unaware of the peril)",
        "High Deck - Marionette": "Represents the presence of a spy or a minion of some greater power -- an encounter with a puppet or an underling",
        "High Deck - Mists": "Represents something unexpected or mysterious that can't be avoided -- a great quest or journey that will try one's spirit",
        "High Deck - Raven": "Represents a hidden source of information -- a fortunate turn of events -- a secret potential for good",
        "High Deck - Seer": "Represents inspiration and keen intellect -- a future event, the outcome of which will hinge on a clever mind",
        "High Deck - Temptress": "Represents one who has been compromised or led astray by temptation or foolishness -- one who tempts others for evil ends",
        "Master of Swords - Warrior": "Represents strength and force personified -- violence -- those who use force to accomplish their goals",
        "1 of Swords - Avenger": "Represents justice and revenge for great wrongs -- those on a quest to rid the world of great evil",
        "2 of Swords - Paladin": "Represents just and noble warriors -- those who live by a code of honor and integrity",
        "3 of Swords - Soldier": "Represents war and sacrifice -- the stamina to endure great hardship",
        "4 of Swords - Mercenary": "Represents inner strength and fortitude -- those who fight for power or wealth",
        "5 of Swords - Myrmidon": "Represents great heroes -- a sudden reversal of fate -- the triumph of the underdog over a mighty enemy",
        "6 of Swords - Berserker": "Represents the brutal and barbaric side of warfare -- bloodlust -- those with a bestial nature",
        "7 of Swords - Hooded One": "Represents bigotry, intolerance, and xenophobia -- a mysterious presence or newcomer",
        "8 of Swords - Dictator": "Represents all that is wrong with government and leadership -- those who rule through fear and violence",
        "9 of Swords - Torturer": "Represents the coming of suffering or merciless cruelty -- one who is irredeemably evil or sadistic",
        "Master of Stars - Wizard": "Represents mystery and riddles -- the unknown -- those who crave magical power and great knowledge",
        "1 of Stars - Transmuter": "Represents a new discovery -- the coming of unexpected things -- unforeseen consequences and chaos",
        "2 of Stars - Diviner": "Represents the pursuit of knowledge tempered by wisdom -- truth and honesty -- sages and prophecy",
        "3 of Stars - Enchanter": "Represents inner turmoil that comes from confusion, fear of failure, or false information",
        "4 of Stars - Abjurer": "Represents those guided by logic and reasoning -- warns of an overlooked clue or piece of information",
        "5 of Stars - Elementalist": "Represents the triumph of nature over civilization -- natural disasters and bountiful harvests",
        "6 of Stars - Evoker": "Represents magical or supernatural power that can't be controlled -- magic for destructive ends",
        "7 of Stars - Illusionist": "Represents lies and deceit -- grand conspiracies -- secret societies -- the presence of a dupe or a saboteur",
        "8 of Stars - Necromancer": "Represents unnatural events and unhealthy obsessions -- those who follow a destructive path",
        "9 of Stars - Conjurer": "Represents the coming of an unexpected supernatural threat -- those who think of themselves as gods",
        "Master of Coins - Rogue": "Represents anyone for whom money is important -- those who believe money is the key to their success",
        "1 of Coins - Swashbuckler": "Represents those who like money yet give it up freely -- likable rogues and rapscallions",
        "2 of Coins - Philanthropist": "Represents charity and giving on a grand scale -- those who use wealth to fight evil and sickness",
        "3 of Coins - Trader": "Represents commerce -- smuggling and black markets -- fair and equitable trades",
        "4 of Coins - Merchant": "Represents a rare commodity or business opportunity -- deceitful or dangerous business transactions",
        "5 of Coins - Guild Member": "Represents like-minded individuals joined together in a common goal -- pride in one's work",
        "6 of Coins - Beggar": "Represents sudden change in economic status or fortune",
        "7 of Coins - Thief": "Represents those who steal or burgle -- a loss of property, beauty, innocence, friendship, or reputation",
        "8 of Coins - Tax Collector": "Represents corruption -- honesty in an otherwise corrupt government or organization",
        "9 of Coins - Miser": "Represents hoarded wealth -- those who are irreversibly unhappy or who think money is meaningless",
        "Master of Glyphs - Priest": "Represents enlightenment -- those who follow a deity, a system of values, or a higher purpose",
        "1 of Glyphs - Monk": "Represents serenity -- inner strength and self-reliance -- supreme confidence bereft of arrogance",
        "2 of Glyphs - Missionary": "Represents those who spread wisdom and faith to others -- warnings of the spread of fear and ignorance",
        "3 of Glyphs - Healer": "Represents healing -- a contagious illness, disease, or curse -- those who practice the healing arts",
        "4 of Glyphs - Shepherd": "Represents those who protect others -- one who bears a burden far too great to be shouldered alone",
        "5 of Glyphs - Druid": "Represents the ambivalence and cruelty of nature and those who feel drawn to it -- inner turmoil",
        "6 of Glyphs - Anarchist": "Represents a fundamental change brought on by one whose beliefs are being put to the test",
        "7 of Glyphs - Charlatan": "Represents liars -- those who profess to believe one thing but actually believe another",
        "8 of Glyphs - Bishop": "Represents strict adherence to a code or a belief -- those who plot, plan, and scheme",
        "9 of Glyphs - Traitor": "Represents betrayal by someone close and trusted -- a weakening or loss of faith",
    },
    "middle": {
        "prophecy": "Focus of the reading. Can indicate how accurate the reading is going to be.",
        "vibe_check": "Focus of the reading. Can indicate how accurate the reading is going to be.",
    },
    "bottom": {
        "prophecy": "Refers to a relevant detail of the past that is important to this flow of events.",
        "vibe_check": "Refers to an important element of the subject's past.",
    },
    "left": {
        "prophecy": "Refers to the present state of the Focus.",
        "vibe_check": "Refers to something that opposes the subject. It can indicate anything from an active enemy, to a possible set-back, or any other 'bad thing' that involves the subject.",
    },
    "top": {
        "prophecy": "Refers to a future action that can bring about some important result.",
        "vibe_check": "Refers to a (possible) future of the subject. This card is always subject to speculation as the future is not set in stone. It generally refers to an impending threat or event, rather than speaking of an 'outcome.'",
    },
    "right": {
        "prophecy": "Refers to the actual result that may occur if this flow is followed.",
        "vibe_check": "Refers to something that is an ally, friend, or boon towards the subject. As with card 3, this can represent anything 'good' that is related to the subject.",
    },
}

export function get_tarokka_data() {
    return data;
}