on:
  push

jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Server
        uses: fjogeleit/http-request-action@master
        with:
            url: 'https://wiki.harebrained.dev/load_changes'
            method: 'GET'