on:
  push

jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Server
        uses: fjogeleit/http-request-action@master
        with:
            url: '$DOMAIN/load_changes'
            method: 'GET'